name: Build and Run

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install pandas numpy matplotlib seaborn

      - name: Run a Script
        run: python example.py
         
